project:
  type: book
  output-dir: docs
   
book:
  title: "Geoinformation with R"
  author: "Moinul Islam"
  date: today
  chapters:
    - index.qmd
    #- lecture_1.qmd
    - lecture_2.qmd
    - lecture_3.qmd
    - lecture_4.qmd
    - lecture_5.qmd
    - lecture_6.qmd
    - lecture_7.qmd
    - lecture_8.qmd
    - lecture_9.qmd
    - lecture_10.qmd
    - lecture_11.qmd
    - lecture_12.qmd
    - references.qmd

bibliography: geoeconomics.bib

format:
  html:
    theme: 
       light: journal
       dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

