# Administrative maps of Japan

-   Load all necessary packages

```{r}
#| message: false
library(tidyverse)
library(sf)
```

- Load the `shapefile` of Japan's administrative divisions

```{r, results='hide'}
#| code-fold: false
jp0_shp <- st_read("data/shapefile/jp_adm0_shp/jpn_admbnda_adm0_2019.shp")
jp1_shp <- st_read("data/shapefile/jp_adm1_shp/jpn_admbnda_adm1_2019.shp") 
jp2_shp <- st_read("data/shapefile/jp_adm2_shp/jpn_admbnda_adm2_2019.shp") 
```
-   Observe the data inside the shape file of `adm0`

```{r}
#| code-fold: false
jp0_shp # for admin level 0
jp1_shp # for admin level 1
jp2_shp # for admin level 2
```

-   Check the geographic coordinate system of your `adm0` shapefile

```{r}
#| code-fold: false
st_crs(jp0_shp) # for admin level 0
st_crs(jp1_shp) # for admin level 1
st_crs(jp2_shp) # for admin level 2
```

-   Plot the map of Japan admin 0

```{r, warning=FALSE}
#| code-fold: false
ggplot(jp0_shp) +
  geom_sf()
```

- Plot the map of Japan admin 1

```{r, warning=FALSE}
#| code-fold: false
ggplot(jp1_shp) +
  geom_sf()
```

- Plot the map of Japan admin 2

```{r, warning=FALSE}
#| code-fold: false
ggplot(jp2_shp) +
  geom_sf()
```
